### ISSUE TITLE
Make footer icons size bigger

### ISSUE THREAD

**Issue by perminder-klair** [zeiq-co/anoop-project#2]

**Comment by Anoop-x-codin** [comment]
should I double the size?

**Comment by perminder-klair** [comment]
yeh that will work!

**Comment by Anoop-x-codin** [comment]
I just done it, please check https://github.com/zeiq-co/anoop-project/commit/ec15835e703e6a6790938ac2d1147dd2fa24c803

**Comment by perminder-klair** [comment]
looks nice, thanks!

**Comment by Anoop-x-codin** [comment]
thanks! closing this issue
