### ISSUE TITLE
Code Cleanup

### ISSUE THREAD

**Issue by perminder-klair** [zeiq-co/anoop-project#5]
Hello @Anoop-x-codin 

I just formatted the code so it's easy to read and understand. you can have a look here what I did: https://github.com/zeiq-co/anoop-project/commit/f5b796bb8af15d872936bef9daa2e05d950fe44a

Rest, very good work on recent commits!

**Comment by Anoop-x-codin** [comment]
Okay! Thank you, I have read it!
